#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);

if(!getenv('REDIS_BACKEND')){

	$dns = sprintf("redis://%s:%s@%s:%s/%d", 
						getenv('YII_REDIS_ALL_USER') ? getenv('YII_REDIS_ALL_USER') : 'root', 
						getenv('YII_REDIS_ALL_PASS'), 
						getenv('YII_REDIS_ALL_HOST'), 
						getenv('YII_REDIS_ALL_PORT'), 
						getenv('YII_REDIS_QUEUE_DBINDEX'));
	putenv("REDIS_BACKEND=$dns");
}

$application = new \common\components\TaskQueue\Application($config);
$exitCode = $application->run();

exit($exitCode);
